 # rule identifiers to exclude from running
disabled_rules:
  - line_length
  - todo
  - identifier_name
  - trailing_whitespace
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - large_tuple
  - type_name
  - function_parameter_count
  - unused_optional_binding
  - array_init
  - blanket_disable_command
  - discouraged_direct_init
  - void_function_in_ternary
  - orphaned_doc_comment
  - operator_whitespace
  - notification_center_detachment
  - empty_enum_arguments
  - for_where
  - closure_parameter_position
  - vertical_whitespace_opening_braces
  - file_length
  - type_body_length

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

force_cast: 
  severity: warning
force_try: 
  severity: warning
force_unwrapping: 
  severity: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
