name: SpliterMax
options:
  bundleIdPrefix: com.splitter
configs:
  Debug-Splitter-DEV: debug
  Release-Splitter-DEV: release
settings:
  configs:
    Debug-Splitter-DEV:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      EXCLUDED_SOURCE_FILE_NAMES: "*/Prod/* */Uat/*"
      SWIFT_LINT_DIFF_ONLY: YES
      SWIFT_LINT_AUTOCORRECT: NO

    Release-Splitter-DEV:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      EXCLUDED_SOURCE_FILE_NAMES: "*/Prod/* */Uat/*"
      SWIFT_LINT_DIFF_ONLY: YES
      SWIFT_LINT_AUTOCORRECT: NO
targets:
  Splitter:
    type: application
    platform: iOS
    # entitlements:
    #   path: Splitter/Splitter.entitlements
    #   properties:
    #     aps-environment: production
    settings:
      base:
        INFOPLIST_FILE: SpliterMax/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: $(inherited)
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
    deploymentTarget: 15.0
    sources:
      - path: SpliterMax
        group: App
        excludes:
          - "**/{*.yml,.*.yml}"
    dependencies:
      - target: Domain
      - target: Services
      - target: Infrastructure
      - target: LocalizationKit
      - target: Utils
      - target: SharedCoreUI
      - target: Explore

    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: sh tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: sh tools/swiftlint.sh

  LocalizationKit:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/LocalizationKit
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/LocalizationKit/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.localizationkit
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    preBuildScripts:
      - name: Swiftgen
        basedOnDependencyAnalysis: false
        script: "cd Shared/LocalizationKit && ../../tools/swiftgen config run --config swiftgen.yml"
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/LocalizationKit && sh ../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/LocalizationKit && sh ../../tools/swiftlint.sh
  Domain:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/Core/Domain
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/Core/Domain/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.domain
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/Core/Domain && sh ../../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/Core/Domain && sh ../../../tools/swiftlint.sh

  Services:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/Core/Services
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/Core/Services/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.services
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/Core/Services && sh ../../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/Core/Services && sh ../../../tools/swiftlint.sh
    dependencies:
      - target: Domain

  Infrastructure:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/Core/Infrastructure
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/Core/Infrastructure/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.infrastructure
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/Core/Infrastructure && sh ../../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/Core/Infrastructure && sh ../../../tools/swiftlint.sh
    dependencies:
      - target: Services
      - target: Domain

  Utils:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/Utils
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/Utils/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.utils
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    dependencies:
      - target: Services
      - target: Domain
    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/Utils && sh ../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/Utils && sh ../../tools/swiftlint.sh

  SharedCoreUI:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/SharedCoreUI
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/SharedCoreUI/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.sharedcoreui
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    dependencies:
      - target: Services
      - target: LocalizationKit
      - target: Utils
    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/SharedCoreUI && sh ../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/SharedCoreUI && sh ../../tools/swiftlint.sh
  Explore:
    type: framework
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: Shared/Explore
        group: Shared
        excludes:
          - "**/{*.yml,.*.yml}"
    info:
      path: Shared/Explore/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.core.explore
        DEFINES_MODULE: false
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    preBuildScripts:
      - name: Swiftformat
        basedOnDependencyAnalysis: false
        script: cd Shared/Explore && sh ../../tools/swiftformat.sh
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: cd Shared/Explore && sh ../../tools/swiftlint.sh
    dependencies:
      - target: SharedCoreUI

  # CoreUI:
  #   type: framework
  #   platform: iOS
  #   deploymentTarget: 14.0
  #   sources:
  #     - path: Shared/CoreUI
  #       group: Shared
  #       excludes:
  #         - "**/{*.yml,.*.yml}"
  #   info:
  #     path: Shared/CoreUI/Info.plist
  #   settings:
  #     base:
  #       PRODUCT_BUNDLE_IDENTIFIER: com.core.coreui
  #       DEFINES_MODULE: false
  #       PROVISIONING_PROFILE_SPECIFIER: ""
  #       ASSETCATALOG_COMPILER_APPICON_NAME: ""
  #   preBuildScripts:
  #     - name: Swiftformat
  #       basedOnDependencyAnalysis: false
  #       script: cd Shared/CoreUI && sh ../../tools/swiftformat.sh
  #     - name: Swiftlint
  #       basedOnDependencyAnalysis: false
  #       script: cd Shared/CoreUI && sh ../../tools/swiftlint.sh
  #   dependencies:
  #     - target: Services
  #     - target: LocalizationKit
  #     - target: Utils
# SplitterUnitTests:
#   type: bundle.unit-test
#   platform: iOS
#   deploymentTarget: 14.0
#   sources:
#     - path: SplitterTests
#       group: AppTests
#   dependencies:
#     - target: Splitter
# SplitterUITests:
#   type: bundle.ui-testing
#   platform: iOS
#   deploymentTarget: 14.0
#   sources:
#     - path: SplitterUITests
#       group: AppTests
#   settings:
#     TEST_TARGET_NAME: Splitter
